package dao.model.base;

import java.io.Serializable;
import java.util.Date;

public class QuestionNaire implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.question_1
     *
     * @mbg.generated
     */
    private String question1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.question_1_other
     *
     * @mbg.generated
     */
    private String question1Other;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.question_2
     *
     * @mbg.generated
     */
    private String question2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.question_2_other
     *
     * @mbg.generated
     */
    private String question2Other;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.question_3
     *
     * @mbg.generated
     */
    private String question3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.question_3_other
     *
     * @mbg.generated
     */
    private String question3Other;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.question_4
     *
     * @mbg.generated
     */
    private String question4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.question_4_other
     *
     * @mbg.generated
     */
    private String question4Other;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.question_5
     *
     * @mbg.generated
     */
    private String question5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.question_5_other
     *
     * @mbg.generated
     */
    private String question5Other;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.question_6
     *
     * @mbg.generated
     */
    private String question6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.question_6_other
     *
     * @mbg.generated
     */
    private String question6Other;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.question_7
     *
     * @mbg.generated
     */
    private String question7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.question_7_other
     *
     * @mbg.generated
     */
    private String question7Other;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.question_8
     *
     * @mbg.generated
     */
    private String question8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.question_8_other
     *
     * @mbg.generated
     */
    private String question8Other;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.question_9
     *
     * @mbg.generated
     */
    private String question9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.question_9_other
     *
     * @mbg.generated
     */
    private String question9Other;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.question_10
     *
     * @mbg.generated
     */
    private String question10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.question_10_other
     *
     * @mbg.generated
     */
    private String question10Other;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.question_11
     *
     * @mbg.generated
     */
    private String question11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.question_11_other
     *
     * @mbg.generated
     */
    private String question11Other;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.question_12
     *
     * @mbg.generated
     */
    private String question12;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.question_12_other
     *
     * @mbg.generated
     */
    private String question12Other;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.question_13
     *
     * @mbg.generated
     */
    private String question13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.question_13_other
     *
     * @mbg.generated
     */
    private String question13Other;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.question_14
     *
     * @mbg.generated
     */
    private String question14;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.question_14_other
     *
     * @mbg.generated
     */
    private String question14Other;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.input_1
     *
     * @mbg.generated
     */
    private String input1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.input_2
     *
     * @mbg.generated
     */
    private String input2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.input_3
     *
     * @mbg.generated
     */
    private String input3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.input_4
     *
     * @mbg.generated
     */
    private String input4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.input_5
     *
     * @mbg.generated
     */
    private String input5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.textarea_1
     *
     * @mbg.generated
     */
    private String textarea1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.textarea_2
     *
     * @mbg.generated
     */
    private String textarea2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_naire.question_id
     *
     * @mbg.generated
     */
    private String questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table question_naire
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.id
     *
     * @return the value of question_naire.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.id
     *
     * @param id the value for question_naire.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.question_1
     *
     * @return the value of question_naire.question_1
     *
     * @mbg.generated
     */
    public String getQuestion1() {
        return question1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.question_1
     *
     * @param question1 the value for question_naire.question_1
     *
     * @mbg.generated
     */
    public void setQuestion1(String question1) {
        this.question1 = question1 == null ? null : question1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.question_1_other
     *
     * @return the value of question_naire.question_1_other
     *
     * @mbg.generated
     */
    public String getQuestion1Other() {
        return question1Other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.question_1_other
     *
     * @param question1Other the value for question_naire.question_1_other
     *
     * @mbg.generated
     */
    public void setQuestion1Other(String question1Other) {
        this.question1Other = question1Other == null ? null : question1Other.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.question_2
     *
     * @return the value of question_naire.question_2
     *
     * @mbg.generated
     */
    public String getQuestion2() {
        return question2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.question_2
     *
     * @param question2 the value for question_naire.question_2
     *
     * @mbg.generated
     */
    public void setQuestion2(String question2) {
        this.question2 = question2 == null ? null : question2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.question_2_other
     *
     * @return the value of question_naire.question_2_other
     *
     * @mbg.generated
     */
    public String getQuestion2Other() {
        return question2Other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.question_2_other
     *
     * @param question2Other the value for question_naire.question_2_other
     *
     * @mbg.generated
     */
    public void setQuestion2Other(String question2Other) {
        this.question2Other = question2Other == null ? null : question2Other.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.question_3
     *
     * @return the value of question_naire.question_3
     *
     * @mbg.generated
     */
    public String getQuestion3() {
        return question3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.question_3
     *
     * @param question3 the value for question_naire.question_3
     *
     * @mbg.generated
     */
    public void setQuestion3(String question3) {
        this.question3 = question3 == null ? null : question3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.question_3_other
     *
     * @return the value of question_naire.question_3_other
     *
     * @mbg.generated
     */
    public String getQuestion3Other() {
        return question3Other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.question_3_other
     *
     * @param question3Other the value for question_naire.question_3_other
     *
     * @mbg.generated
     */
    public void setQuestion3Other(String question3Other) {
        this.question3Other = question3Other == null ? null : question3Other.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.question_4
     *
     * @return the value of question_naire.question_4
     *
     * @mbg.generated
     */
    public String getQuestion4() {
        return question4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.question_4
     *
     * @param question4 the value for question_naire.question_4
     *
     * @mbg.generated
     */
    public void setQuestion4(String question4) {
        this.question4 = question4 == null ? null : question4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.question_4_other
     *
     * @return the value of question_naire.question_4_other
     *
     * @mbg.generated
     */
    public String getQuestion4Other() {
        return question4Other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.question_4_other
     *
     * @param question4Other the value for question_naire.question_4_other
     *
     * @mbg.generated
     */
    public void setQuestion4Other(String question4Other) {
        this.question4Other = question4Other == null ? null : question4Other.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.question_5
     *
     * @return the value of question_naire.question_5
     *
     * @mbg.generated
     */
    public String getQuestion5() {
        return question5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.question_5
     *
     * @param question5 the value for question_naire.question_5
     *
     * @mbg.generated
     */
    public void setQuestion5(String question5) {
        this.question5 = question5 == null ? null : question5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.question_5_other
     *
     * @return the value of question_naire.question_5_other
     *
     * @mbg.generated
     */
    public String getQuestion5Other() {
        return question5Other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.question_5_other
     *
     * @param question5Other the value for question_naire.question_5_other
     *
     * @mbg.generated
     */
    public void setQuestion5Other(String question5Other) {
        this.question5Other = question5Other == null ? null : question5Other.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.question_6
     *
     * @return the value of question_naire.question_6
     *
     * @mbg.generated
     */
    public String getQuestion6() {
        return question6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.question_6
     *
     * @param question6 the value for question_naire.question_6
     *
     * @mbg.generated
     */
    public void setQuestion6(String question6) {
        this.question6 = question6 == null ? null : question6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.question_6_other
     *
     * @return the value of question_naire.question_6_other
     *
     * @mbg.generated
     */
    public String getQuestion6Other() {
        return question6Other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.question_6_other
     *
     * @param question6Other the value for question_naire.question_6_other
     *
     * @mbg.generated
     */
    public void setQuestion6Other(String question6Other) {
        this.question6Other = question6Other == null ? null : question6Other.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.question_7
     *
     * @return the value of question_naire.question_7
     *
     * @mbg.generated
     */
    public String getQuestion7() {
        return question7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.question_7
     *
     * @param question7 the value for question_naire.question_7
     *
     * @mbg.generated
     */
    public void setQuestion7(String question7) {
        this.question7 = question7 == null ? null : question7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.question_7_other
     *
     * @return the value of question_naire.question_7_other
     *
     * @mbg.generated
     */
    public String getQuestion7Other() {
        return question7Other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.question_7_other
     *
     * @param question7Other the value for question_naire.question_7_other
     *
     * @mbg.generated
     */
    public void setQuestion7Other(String question7Other) {
        this.question7Other = question7Other == null ? null : question7Other.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.question_8
     *
     * @return the value of question_naire.question_8
     *
     * @mbg.generated
     */
    public String getQuestion8() {
        return question8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.question_8
     *
     * @param question8 the value for question_naire.question_8
     *
     * @mbg.generated
     */
    public void setQuestion8(String question8) {
        this.question8 = question8 == null ? null : question8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.question_8_other
     *
     * @return the value of question_naire.question_8_other
     *
     * @mbg.generated
     */
    public String getQuestion8Other() {
        return question8Other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.question_8_other
     *
     * @param question8Other the value for question_naire.question_8_other
     *
     * @mbg.generated
     */
    public void setQuestion8Other(String question8Other) {
        this.question8Other = question8Other == null ? null : question8Other.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.question_9
     *
     * @return the value of question_naire.question_9
     *
     * @mbg.generated
     */
    public String getQuestion9() {
        return question9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.question_9
     *
     * @param question9 the value for question_naire.question_9
     *
     * @mbg.generated
     */
    public void setQuestion9(String question9) {
        this.question9 = question9 == null ? null : question9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.question_9_other
     *
     * @return the value of question_naire.question_9_other
     *
     * @mbg.generated
     */
    public String getQuestion9Other() {
        return question9Other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.question_9_other
     *
     * @param question9Other the value for question_naire.question_9_other
     *
     * @mbg.generated
     */
    public void setQuestion9Other(String question9Other) {
        this.question9Other = question9Other == null ? null : question9Other.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.question_10
     *
     * @return the value of question_naire.question_10
     *
     * @mbg.generated
     */
    public String getQuestion10() {
        return question10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.question_10
     *
     * @param question10 the value for question_naire.question_10
     *
     * @mbg.generated
     */
    public void setQuestion10(String question10) {
        this.question10 = question10 == null ? null : question10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.question_10_other
     *
     * @return the value of question_naire.question_10_other
     *
     * @mbg.generated
     */
    public String getQuestion10Other() {
        return question10Other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.question_10_other
     *
     * @param question10Other the value for question_naire.question_10_other
     *
     * @mbg.generated
     */
    public void setQuestion10Other(String question10Other) {
        this.question10Other = question10Other == null ? null : question10Other.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.question_11
     *
     * @return the value of question_naire.question_11
     *
     * @mbg.generated
     */
    public String getQuestion11() {
        return question11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.question_11
     *
     * @param question11 the value for question_naire.question_11
     *
     * @mbg.generated
     */
    public void setQuestion11(String question11) {
        this.question11 = question11 == null ? null : question11.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.question_11_other
     *
     * @return the value of question_naire.question_11_other
     *
     * @mbg.generated
     */
    public String getQuestion11Other() {
        return question11Other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.question_11_other
     *
     * @param question11Other the value for question_naire.question_11_other
     *
     * @mbg.generated
     */
    public void setQuestion11Other(String question11Other) {
        this.question11Other = question11Other == null ? null : question11Other.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.question_12
     *
     * @return the value of question_naire.question_12
     *
     * @mbg.generated
     */
    public String getQuestion12() {
        return question12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.question_12
     *
     * @param question12 the value for question_naire.question_12
     *
     * @mbg.generated
     */
    public void setQuestion12(String question12) {
        this.question12 = question12 == null ? null : question12.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.question_12_other
     *
     * @return the value of question_naire.question_12_other
     *
     * @mbg.generated
     */
    public String getQuestion12Other() {
        return question12Other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.question_12_other
     *
     * @param question12Other the value for question_naire.question_12_other
     *
     * @mbg.generated
     */
    public void setQuestion12Other(String question12Other) {
        this.question12Other = question12Other == null ? null : question12Other.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.question_13
     *
     * @return the value of question_naire.question_13
     *
     * @mbg.generated
     */
    public String getQuestion13() {
        return question13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.question_13
     *
     * @param question13 the value for question_naire.question_13
     *
     * @mbg.generated
     */
    public void setQuestion13(String question13) {
        this.question13 = question13 == null ? null : question13.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.question_13_other
     *
     * @return the value of question_naire.question_13_other
     *
     * @mbg.generated
     */
    public String getQuestion13Other() {
        return question13Other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.question_13_other
     *
     * @param question13Other the value for question_naire.question_13_other
     *
     * @mbg.generated
     */
    public void setQuestion13Other(String question13Other) {
        this.question13Other = question13Other == null ? null : question13Other.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.question_14
     *
     * @return the value of question_naire.question_14
     *
     * @mbg.generated
     */
    public String getQuestion14() {
        return question14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.question_14
     *
     * @param question14 the value for question_naire.question_14
     *
     * @mbg.generated
     */
    public void setQuestion14(String question14) {
        this.question14 = question14 == null ? null : question14.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.question_14_other
     *
     * @return the value of question_naire.question_14_other
     *
     * @mbg.generated
     */
    public String getQuestion14Other() {
        return question14Other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.question_14_other
     *
     * @param question14Other the value for question_naire.question_14_other
     *
     * @mbg.generated
     */
    public void setQuestion14Other(String question14Other) {
        this.question14Other = question14Other == null ? null : question14Other.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.create_time
     *
     * @return the value of question_naire.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.create_time
     *
     * @param createTime the value for question_naire.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.input_1
     *
     * @return the value of question_naire.input_1
     *
     * @mbg.generated
     */
    public String getInput1() {
        return input1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.input_1
     *
     * @param input1 the value for question_naire.input_1
     *
     * @mbg.generated
     */
    public void setInput1(String input1) {
        this.input1 = input1 == null ? null : input1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.input_2
     *
     * @return the value of question_naire.input_2
     *
     * @mbg.generated
     */
    public String getInput2() {
        return input2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.input_2
     *
     * @param input2 the value for question_naire.input_2
     *
     * @mbg.generated
     */
    public void setInput2(String input2) {
        this.input2 = input2 == null ? null : input2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.input_3
     *
     * @return the value of question_naire.input_3
     *
     * @mbg.generated
     */
    public String getInput3() {
        return input3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.input_3
     *
     * @param input3 the value for question_naire.input_3
     *
     * @mbg.generated
     */
    public void setInput3(String input3) {
        this.input3 = input3 == null ? null : input3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.input_4
     *
     * @return the value of question_naire.input_4
     *
     * @mbg.generated
     */
    public String getInput4() {
        return input4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.input_4
     *
     * @param input4 the value for question_naire.input_4
     *
     * @mbg.generated
     */
    public void setInput4(String input4) {
        this.input4 = input4 == null ? null : input4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.input_5
     *
     * @return the value of question_naire.input_5
     *
     * @mbg.generated
     */
    public String getInput5() {
        return input5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.input_5
     *
     * @param input5 the value for question_naire.input_5
     *
     * @mbg.generated
     */
    public void setInput5(String input5) {
        this.input5 = input5 == null ? null : input5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.textarea_1
     *
     * @return the value of question_naire.textarea_1
     *
     * @mbg.generated
     */
    public String getTextarea1() {
        return textarea1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.textarea_1
     *
     * @param textarea1 the value for question_naire.textarea_1
     *
     * @mbg.generated
     */
    public void setTextarea1(String textarea1) {
        this.textarea1 = textarea1 == null ? null : textarea1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.textarea_2
     *
     * @return the value of question_naire.textarea_2
     *
     * @mbg.generated
     */
    public String getTextarea2() {
        return textarea2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.textarea_2
     *
     * @param textarea2 the value for question_naire.textarea_2
     *
     * @mbg.generated
     */
    public void setTextarea2(String textarea2) {
        this.textarea2 = textarea2 == null ? null : textarea2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_naire.question_id
     *
     * @return the value of question_naire.question_id
     *
     * @mbg.generated
     */
    public String getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_naire.question_id
     *
     * @param questionId the value for question_naire.question_id
     *
     * @mbg.generated
     */
    public void setQuestionId(String questionId) {
        this.questionId = questionId == null ? null : questionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_naire
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        QuestionNaire other = (QuestionNaire) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getQuestion1() == null ? other.getQuestion1() == null : this.getQuestion1().equals(other.getQuestion1()))
            && (this.getQuestion1Other() == null ? other.getQuestion1Other() == null : this.getQuestion1Other().equals(other.getQuestion1Other()))
            && (this.getQuestion2() == null ? other.getQuestion2() == null : this.getQuestion2().equals(other.getQuestion2()))
            && (this.getQuestion2Other() == null ? other.getQuestion2Other() == null : this.getQuestion2Other().equals(other.getQuestion2Other()))
            && (this.getQuestion3() == null ? other.getQuestion3() == null : this.getQuestion3().equals(other.getQuestion3()))
            && (this.getQuestion3Other() == null ? other.getQuestion3Other() == null : this.getQuestion3Other().equals(other.getQuestion3Other()))
            && (this.getQuestion4() == null ? other.getQuestion4() == null : this.getQuestion4().equals(other.getQuestion4()))
            && (this.getQuestion4Other() == null ? other.getQuestion4Other() == null : this.getQuestion4Other().equals(other.getQuestion4Other()))
            && (this.getQuestion5() == null ? other.getQuestion5() == null : this.getQuestion5().equals(other.getQuestion5()))
            && (this.getQuestion5Other() == null ? other.getQuestion5Other() == null : this.getQuestion5Other().equals(other.getQuestion5Other()))
            && (this.getQuestion6() == null ? other.getQuestion6() == null : this.getQuestion6().equals(other.getQuestion6()))
            && (this.getQuestion6Other() == null ? other.getQuestion6Other() == null : this.getQuestion6Other().equals(other.getQuestion6Other()))
            && (this.getQuestion7() == null ? other.getQuestion7() == null : this.getQuestion7().equals(other.getQuestion7()))
            && (this.getQuestion7Other() == null ? other.getQuestion7Other() == null : this.getQuestion7Other().equals(other.getQuestion7Other()))
            && (this.getQuestion8() == null ? other.getQuestion8() == null : this.getQuestion8().equals(other.getQuestion8()))
            && (this.getQuestion8Other() == null ? other.getQuestion8Other() == null : this.getQuestion8Other().equals(other.getQuestion8Other()))
            && (this.getQuestion9() == null ? other.getQuestion9() == null : this.getQuestion9().equals(other.getQuestion9()))
            && (this.getQuestion9Other() == null ? other.getQuestion9Other() == null : this.getQuestion9Other().equals(other.getQuestion9Other()))
            && (this.getQuestion10() == null ? other.getQuestion10() == null : this.getQuestion10().equals(other.getQuestion10()))
            && (this.getQuestion10Other() == null ? other.getQuestion10Other() == null : this.getQuestion10Other().equals(other.getQuestion10Other()))
            && (this.getQuestion11() == null ? other.getQuestion11() == null : this.getQuestion11().equals(other.getQuestion11()))
            && (this.getQuestion11Other() == null ? other.getQuestion11Other() == null : this.getQuestion11Other().equals(other.getQuestion11Other()))
            && (this.getQuestion12() == null ? other.getQuestion12() == null : this.getQuestion12().equals(other.getQuestion12()))
            && (this.getQuestion12Other() == null ? other.getQuestion12Other() == null : this.getQuestion12Other().equals(other.getQuestion12Other()))
            && (this.getQuestion13() == null ? other.getQuestion13() == null : this.getQuestion13().equals(other.getQuestion13()))
            && (this.getQuestion13Other() == null ? other.getQuestion13Other() == null : this.getQuestion13Other().equals(other.getQuestion13Other()))
            && (this.getQuestion14() == null ? other.getQuestion14() == null : this.getQuestion14().equals(other.getQuestion14()))
            && (this.getQuestion14Other() == null ? other.getQuestion14Other() == null : this.getQuestion14Other().equals(other.getQuestion14Other()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getInput1() == null ? other.getInput1() == null : this.getInput1().equals(other.getInput1()))
            && (this.getInput2() == null ? other.getInput2() == null : this.getInput2().equals(other.getInput2()))
            && (this.getInput3() == null ? other.getInput3() == null : this.getInput3().equals(other.getInput3()))
            && (this.getInput4() == null ? other.getInput4() == null : this.getInput4().equals(other.getInput4()))
            && (this.getInput5() == null ? other.getInput5() == null : this.getInput5().equals(other.getInput5()))
            && (this.getTextarea1() == null ? other.getTextarea1() == null : this.getTextarea1().equals(other.getTextarea1()))
            && (this.getTextarea2() == null ? other.getTextarea2() == null : this.getTextarea2().equals(other.getTextarea2()))
            && (this.getQuestionId() == null ? other.getQuestionId() == null : this.getQuestionId().equals(other.getQuestionId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_naire
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getQuestion1() == null) ? 0 : getQuestion1().hashCode());
        result = prime * result + ((getQuestion1Other() == null) ? 0 : getQuestion1Other().hashCode());
        result = prime * result + ((getQuestion2() == null) ? 0 : getQuestion2().hashCode());
        result = prime * result + ((getQuestion2Other() == null) ? 0 : getQuestion2Other().hashCode());
        result = prime * result + ((getQuestion3() == null) ? 0 : getQuestion3().hashCode());
        result = prime * result + ((getQuestion3Other() == null) ? 0 : getQuestion3Other().hashCode());
        result = prime * result + ((getQuestion4() == null) ? 0 : getQuestion4().hashCode());
        result = prime * result + ((getQuestion4Other() == null) ? 0 : getQuestion4Other().hashCode());
        result = prime * result + ((getQuestion5() == null) ? 0 : getQuestion5().hashCode());
        result = prime * result + ((getQuestion5Other() == null) ? 0 : getQuestion5Other().hashCode());
        result = prime * result + ((getQuestion6() == null) ? 0 : getQuestion6().hashCode());
        result = prime * result + ((getQuestion6Other() == null) ? 0 : getQuestion6Other().hashCode());
        result = prime * result + ((getQuestion7() == null) ? 0 : getQuestion7().hashCode());
        result = prime * result + ((getQuestion7Other() == null) ? 0 : getQuestion7Other().hashCode());
        result = prime * result + ((getQuestion8() == null) ? 0 : getQuestion8().hashCode());
        result = prime * result + ((getQuestion8Other() == null) ? 0 : getQuestion8Other().hashCode());
        result = prime * result + ((getQuestion9() == null) ? 0 : getQuestion9().hashCode());
        result = prime * result + ((getQuestion9Other() == null) ? 0 : getQuestion9Other().hashCode());
        result = prime * result + ((getQuestion10() == null) ? 0 : getQuestion10().hashCode());
        result = prime * result + ((getQuestion10Other() == null) ? 0 : getQuestion10Other().hashCode());
        result = prime * result + ((getQuestion11() == null) ? 0 : getQuestion11().hashCode());
        result = prime * result + ((getQuestion11Other() == null) ? 0 : getQuestion11Other().hashCode());
        result = prime * result + ((getQuestion12() == null) ? 0 : getQuestion12().hashCode());
        result = prime * result + ((getQuestion12Other() == null) ? 0 : getQuestion12Other().hashCode());
        result = prime * result + ((getQuestion13() == null) ? 0 : getQuestion13().hashCode());
        result = prime * result + ((getQuestion13Other() == null) ? 0 : getQuestion13Other().hashCode());
        result = prime * result + ((getQuestion14() == null) ? 0 : getQuestion14().hashCode());
        result = prime * result + ((getQuestion14Other() == null) ? 0 : getQuestion14Other().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getInput1() == null) ? 0 : getInput1().hashCode());
        result = prime * result + ((getInput2() == null) ? 0 : getInput2().hashCode());
        result = prime * result + ((getInput3() == null) ? 0 : getInput3().hashCode());
        result = prime * result + ((getInput4() == null) ? 0 : getInput4().hashCode());
        result = prime * result + ((getInput5() == null) ? 0 : getInput5().hashCode());
        result = prime * result + ((getTextarea1() == null) ? 0 : getTextarea1().hashCode());
        result = prime * result + ((getTextarea2() == null) ? 0 : getTextarea2().hashCode());
        result = prime * result + ((getQuestionId() == null) ? 0 : getQuestionId().hashCode());
        return result;
    }
}