// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QuestionAnswer.proto

package protobuf.http;

public final class QuestionAnswer {
  private QuestionAnswer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface QuestionAnswerCOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.http.QuestionAnswerC)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 hOpCode = 1;</code>
     */
    int getHOpCode();

    /**
     * <code>repeated string questionList = 2;</code>
     */
    java.util.List<java.lang.String>
        getQuestionListList();
    /**
     * <code>repeated string questionList = 2;</code>
     */
    int getQuestionListCount();
    /**
     * <code>repeated string questionList = 2;</code>
     */
    java.lang.String getQuestionList(int index);
    /**
     * <code>repeated string questionList = 2;</code>
     */
    com.google.protobuf.ByteString
        getQuestionListBytes(int index);

    /**
     * <code>repeated string questionOtherList = 3;</code>
     */
    java.util.List<java.lang.String>
        getQuestionOtherListList();
    /**
     * <code>repeated string questionOtherList = 3;</code>
     */
    int getQuestionOtherListCount();
    /**
     * <code>repeated string questionOtherList = 3;</code>
     */
    java.lang.String getQuestionOtherList(int index);
    /**
     * <code>repeated string questionOtherList = 3;</code>
     */
    com.google.protobuf.ByteString
        getQuestionOtherListBytes(int index);

    /**
     * <code>repeated string inputList = 4;</code>
     */
    java.util.List<java.lang.String>
        getInputListList();
    /**
     * <code>repeated string inputList = 4;</code>
     */
    int getInputListCount();
    /**
     * <code>repeated string inputList = 4;</code>
     */
    java.lang.String getInputList(int index);
    /**
     * <code>repeated string inputList = 4;</code>
     */
    com.google.protobuf.ByteString
        getInputListBytes(int index);

    /**
     * <code>repeated string textAreaList = 5;</code>
     */
    java.util.List<java.lang.String>
        getTextAreaListList();
    /**
     * <code>repeated string textAreaList = 5;</code>
     */
    int getTextAreaListCount();
    /**
     * <code>repeated string textAreaList = 5;</code>
     */
    java.lang.String getTextAreaList(int index);
    /**
     * <code>repeated string textAreaList = 5;</code>
     */
    com.google.protobuf.ByteString
        getTextAreaListBytes(int index);

    /**
     * <code>optional string questionId = 6;</code>
     */
    java.lang.String getQuestionId();
    /**
     * <code>optional string questionId = 6;</code>
     */
    com.google.protobuf.ByteString
        getQuestionIdBytes();
  }
  /**
   * Protobuf type {@code protobuf.http.QuestionAnswerC}
   */
  public  static final class QuestionAnswerC extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.http.QuestionAnswerC)
      QuestionAnswerCOrBuilder {
    // Use QuestionAnswerC.newBuilder() to construct.
    private QuestionAnswerC(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QuestionAnswerC() {
      hOpCode_ = 0;
      questionList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      questionOtherList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      inputList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      textAreaList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      questionId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private QuestionAnswerC(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              hOpCode_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                questionList_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              questionList_.add(s);
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                questionOtherList_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              questionOtherList_.add(s);
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                inputList_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              inputList_.add(s);
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                textAreaList_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              textAreaList_.add(s);
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              questionId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          questionList_ = questionList_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          questionOtherList_ = questionOtherList_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          inputList_ = inputList_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          textAreaList_ = textAreaList_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.http.QuestionAnswer.internal_static_protobuf_http_QuestionAnswerC_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.http.QuestionAnswer.internal_static_protobuf_http_QuestionAnswerC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.http.QuestionAnswer.QuestionAnswerC.class, protobuf.http.QuestionAnswer.QuestionAnswerC.Builder.class);
    }

    private int bitField0_;
    public static final int HOPCODE_FIELD_NUMBER = 1;
    private int hOpCode_;
    /**
     * <code>optional int32 hOpCode = 1;</code>
     */
    public int getHOpCode() {
      return hOpCode_;
    }

    public static final int QUESTIONLIST_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList questionList_;
    /**
     * <code>repeated string questionList = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getQuestionListList() {
      return questionList_;
    }
    /**
     * <code>repeated string questionList = 2;</code>
     */
    public int getQuestionListCount() {
      return questionList_.size();
    }
    /**
     * <code>repeated string questionList = 2;</code>
     */
    public java.lang.String getQuestionList(int index) {
      return questionList_.get(index);
    }
    /**
     * <code>repeated string questionList = 2;</code>
     */
    public com.google.protobuf.ByteString
        getQuestionListBytes(int index) {
      return questionList_.getByteString(index);
    }

    public static final int QUESTIONOTHERLIST_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList questionOtherList_;
    /**
     * <code>repeated string questionOtherList = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getQuestionOtherListList() {
      return questionOtherList_;
    }
    /**
     * <code>repeated string questionOtherList = 3;</code>
     */
    public int getQuestionOtherListCount() {
      return questionOtherList_.size();
    }
    /**
     * <code>repeated string questionOtherList = 3;</code>
     */
    public java.lang.String getQuestionOtherList(int index) {
      return questionOtherList_.get(index);
    }
    /**
     * <code>repeated string questionOtherList = 3;</code>
     */
    public com.google.protobuf.ByteString
        getQuestionOtherListBytes(int index) {
      return questionOtherList_.getByteString(index);
    }

    public static final int INPUTLIST_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList inputList_;
    /**
     * <code>repeated string inputList = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getInputListList() {
      return inputList_;
    }
    /**
     * <code>repeated string inputList = 4;</code>
     */
    public int getInputListCount() {
      return inputList_.size();
    }
    /**
     * <code>repeated string inputList = 4;</code>
     */
    public java.lang.String getInputList(int index) {
      return inputList_.get(index);
    }
    /**
     * <code>repeated string inputList = 4;</code>
     */
    public com.google.protobuf.ByteString
        getInputListBytes(int index) {
      return inputList_.getByteString(index);
    }

    public static final int TEXTAREALIST_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList textAreaList_;
    /**
     * <code>repeated string textAreaList = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getTextAreaListList() {
      return textAreaList_;
    }
    /**
     * <code>repeated string textAreaList = 5;</code>
     */
    public int getTextAreaListCount() {
      return textAreaList_.size();
    }
    /**
     * <code>repeated string textAreaList = 5;</code>
     */
    public java.lang.String getTextAreaList(int index) {
      return textAreaList_.get(index);
    }
    /**
     * <code>repeated string textAreaList = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTextAreaListBytes(int index) {
      return textAreaList_.getByteString(index);
    }

    public static final int QUESTIONID_FIELD_NUMBER = 6;
    private volatile java.lang.Object questionId_;
    /**
     * <code>optional string questionId = 6;</code>
     */
    public java.lang.String getQuestionId() {
      java.lang.Object ref = questionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        questionId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string questionId = 6;</code>
     */
    public com.google.protobuf.ByteString
        getQuestionIdBytes() {
      java.lang.Object ref = questionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        questionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hOpCode_ != 0) {
        output.writeInt32(1, hOpCode_);
      }
      for (int i = 0; i < questionList_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, questionList_.getRaw(i));
      }
      for (int i = 0; i < questionOtherList_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, questionOtherList_.getRaw(i));
      }
      for (int i = 0; i < inputList_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, inputList_.getRaw(i));
      }
      for (int i = 0; i < textAreaList_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, textAreaList_.getRaw(i));
      }
      if (!getQuestionIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, questionId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (hOpCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, hOpCode_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < questionList_.size(); i++) {
          dataSize += computeStringSizeNoTag(questionList_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getQuestionListList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < questionOtherList_.size(); i++) {
          dataSize += computeStringSizeNoTag(questionOtherList_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getQuestionOtherListList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < inputList_.size(); i++) {
          dataSize += computeStringSizeNoTag(inputList_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getInputListList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < textAreaList_.size(); i++) {
          dataSize += computeStringSizeNoTag(textAreaList_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getTextAreaListList().size();
      }
      if (!getQuestionIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, questionId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.http.QuestionAnswer.QuestionAnswerC)) {
        return super.equals(obj);
      }
      protobuf.http.QuestionAnswer.QuestionAnswerC other = (protobuf.http.QuestionAnswer.QuestionAnswerC) obj;

      boolean result = true;
      result = result && (getHOpCode()
          == other.getHOpCode());
      result = result && getQuestionListList()
          .equals(other.getQuestionListList());
      result = result && getQuestionOtherListList()
          .equals(other.getQuestionOtherListList());
      result = result && getInputListList()
          .equals(other.getInputListList());
      result = result && getTextAreaListList()
          .equals(other.getTextAreaListList());
      result = result && getQuestionId()
          .equals(other.getQuestionId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + HOPCODE_FIELD_NUMBER;
      hash = (53 * hash) + getHOpCode();
      if (getQuestionListCount() > 0) {
        hash = (37 * hash) + QUESTIONLIST_FIELD_NUMBER;
        hash = (53 * hash) + getQuestionListList().hashCode();
      }
      if (getQuestionOtherListCount() > 0) {
        hash = (37 * hash) + QUESTIONOTHERLIST_FIELD_NUMBER;
        hash = (53 * hash) + getQuestionOtherListList().hashCode();
      }
      if (getInputListCount() > 0) {
        hash = (37 * hash) + INPUTLIST_FIELD_NUMBER;
        hash = (53 * hash) + getInputListList().hashCode();
      }
      if (getTextAreaListCount() > 0) {
        hash = (37 * hash) + TEXTAREALIST_FIELD_NUMBER;
        hash = (53 * hash) + getTextAreaListList().hashCode();
      }
      hash = (37 * hash) + QUESTIONID_FIELD_NUMBER;
      hash = (53 * hash) + getQuestionId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.http.QuestionAnswer.QuestionAnswerC parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.http.QuestionAnswer.QuestionAnswerC parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.http.QuestionAnswer.QuestionAnswerC parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.http.QuestionAnswer.QuestionAnswerC parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.http.QuestionAnswer.QuestionAnswerC parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.http.QuestionAnswer.QuestionAnswerC parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.http.QuestionAnswer.QuestionAnswerC parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.http.QuestionAnswer.QuestionAnswerC parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.http.QuestionAnswer.QuestionAnswerC parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.http.QuestionAnswer.QuestionAnswerC parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.http.QuestionAnswer.QuestionAnswerC prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.http.QuestionAnswerC}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.http.QuestionAnswerC)
        protobuf.http.QuestionAnswer.QuestionAnswerCOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.http.QuestionAnswer.internal_static_protobuf_http_QuestionAnswerC_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.http.QuestionAnswer.internal_static_protobuf_http_QuestionAnswerC_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.http.QuestionAnswer.QuestionAnswerC.class, protobuf.http.QuestionAnswer.QuestionAnswerC.Builder.class);
      }

      // Construct using protobuf.http.QuestionAnswer.QuestionAnswerC.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        hOpCode_ = 0;

        questionList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        questionOtherList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        inputList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        textAreaList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        questionId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.http.QuestionAnswer.internal_static_protobuf_http_QuestionAnswerC_descriptor;
      }

      public protobuf.http.QuestionAnswer.QuestionAnswerC getDefaultInstanceForType() {
        return protobuf.http.QuestionAnswer.QuestionAnswerC.getDefaultInstance();
      }

      public protobuf.http.QuestionAnswer.QuestionAnswerC build() {
        protobuf.http.QuestionAnswer.QuestionAnswerC result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.http.QuestionAnswer.QuestionAnswerC buildPartial() {
        protobuf.http.QuestionAnswer.QuestionAnswerC result = new protobuf.http.QuestionAnswer.QuestionAnswerC(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.hOpCode_ = hOpCode_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          questionList_ = questionList_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.questionList_ = questionList_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          questionOtherList_ = questionOtherList_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.questionOtherList_ = questionOtherList_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          inputList_ = inputList_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.inputList_ = inputList_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          textAreaList_ = textAreaList_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.textAreaList_ = textAreaList_;
        result.questionId_ = questionId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.http.QuestionAnswer.QuestionAnswerC) {
          return mergeFrom((protobuf.http.QuestionAnswer.QuestionAnswerC)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.http.QuestionAnswer.QuestionAnswerC other) {
        if (other == protobuf.http.QuestionAnswer.QuestionAnswerC.getDefaultInstance()) return this;
        if (other.getHOpCode() != 0) {
          setHOpCode(other.getHOpCode());
        }
        if (!other.questionList_.isEmpty()) {
          if (questionList_.isEmpty()) {
            questionList_ = other.questionList_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureQuestionListIsMutable();
            questionList_.addAll(other.questionList_);
          }
          onChanged();
        }
        if (!other.questionOtherList_.isEmpty()) {
          if (questionOtherList_.isEmpty()) {
            questionOtherList_ = other.questionOtherList_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureQuestionOtherListIsMutable();
            questionOtherList_.addAll(other.questionOtherList_);
          }
          onChanged();
        }
        if (!other.inputList_.isEmpty()) {
          if (inputList_.isEmpty()) {
            inputList_ = other.inputList_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureInputListIsMutable();
            inputList_.addAll(other.inputList_);
          }
          onChanged();
        }
        if (!other.textAreaList_.isEmpty()) {
          if (textAreaList_.isEmpty()) {
            textAreaList_ = other.textAreaList_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureTextAreaListIsMutable();
            textAreaList_.addAll(other.textAreaList_);
          }
          onChanged();
        }
        if (!other.getQuestionId().isEmpty()) {
          questionId_ = other.questionId_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.http.QuestionAnswer.QuestionAnswerC parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.http.QuestionAnswer.QuestionAnswerC) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int hOpCode_ ;
      /**
       * <code>optional int32 hOpCode = 1;</code>
       */
      public int getHOpCode() {
        return hOpCode_;
      }
      /**
       * <code>optional int32 hOpCode = 1;</code>
       */
      public Builder setHOpCode(int value) {
        
        hOpCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 hOpCode = 1;</code>
       */
      public Builder clearHOpCode() {
        
        hOpCode_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList questionList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureQuestionListIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          questionList_ = new com.google.protobuf.LazyStringArrayList(questionList_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string questionList = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getQuestionListList() {
        return questionList_.getUnmodifiableView();
      }
      /**
       * <code>repeated string questionList = 2;</code>
       */
      public int getQuestionListCount() {
        return questionList_.size();
      }
      /**
       * <code>repeated string questionList = 2;</code>
       */
      public java.lang.String getQuestionList(int index) {
        return questionList_.get(index);
      }
      /**
       * <code>repeated string questionList = 2;</code>
       */
      public com.google.protobuf.ByteString
          getQuestionListBytes(int index) {
        return questionList_.getByteString(index);
      }
      /**
       * <code>repeated string questionList = 2;</code>
       */
      public Builder setQuestionList(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureQuestionListIsMutable();
        questionList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string questionList = 2;</code>
       */
      public Builder addQuestionList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureQuestionListIsMutable();
        questionList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string questionList = 2;</code>
       */
      public Builder addAllQuestionList(
          java.lang.Iterable<java.lang.String> values) {
        ensureQuestionListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, questionList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string questionList = 2;</code>
       */
      public Builder clearQuestionList() {
        questionList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string questionList = 2;</code>
       */
      public Builder addQuestionListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureQuestionListIsMutable();
        questionList_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList questionOtherList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureQuestionOtherListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          questionOtherList_ = new com.google.protobuf.LazyStringArrayList(questionOtherList_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string questionOtherList = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getQuestionOtherListList() {
        return questionOtherList_.getUnmodifiableView();
      }
      /**
       * <code>repeated string questionOtherList = 3;</code>
       */
      public int getQuestionOtherListCount() {
        return questionOtherList_.size();
      }
      /**
       * <code>repeated string questionOtherList = 3;</code>
       */
      public java.lang.String getQuestionOtherList(int index) {
        return questionOtherList_.get(index);
      }
      /**
       * <code>repeated string questionOtherList = 3;</code>
       */
      public com.google.protobuf.ByteString
          getQuestionOtherListBytes(int index) {
        return questionOtherList_.getByteString(index);
      }
      /**
       * <code>repeated string questionOtherList = 3;</code>
       */
      public Builder setQuestionOtherList(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureQuestionOtherListIsMutable();
        questionOtherList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string questionOtherList = 3;</code>
       */
      public Builder addQuestionOtherList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureQuestionOtherListIsMutable();
        questionOtherList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string questionOtherList = 3;</code>
       */
      public Builder addAllQuestionOtherList(
          java.lang.Iterable<java.lang.String> values) {
        ensureQuestionOtherListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, questionOtherList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string questionOtherList = 3;</code>
       */
      public Builder clearQuestionOtherList() {
        questionOtherList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string questionOtherList = 3;</code>
       */
      public Builder addQuestionOtherListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureQuestionOtherListIsMutable();
        questionOtherList_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList inputList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureInputListIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          inputList_ = new com.google.protobuf.LazyStringArrayList(inputList_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string inputList = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getInputListList() {
        return inputList_.getUnmodifiableView();
      }
      /**
       * <code>repeated string inputList = 4;</code>
       */
      public int getInputListCount() {
        return inputList_.size();
      }
      /**
       * <code>repeated string inputList = 4;</code>
       */
      public java.lang.String getInputList(int index) {
        return inputList_.get(index);
      }
      /**
       * <code>repeated string inputList = 4;</code>
       */
      public com.google.protobuf.ByteString
          getInputListBytes(int index) {
        return inputList_.getByteString(index);
      }
      /**
       * <code>repeated string inputList = 4;</code>
       */
      public Builder setInputList(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInputListIsMutable();
        inputList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string inputList = 4;</code>
       */
      public Builder addInputList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInputListIsMutable();
        inputList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string inputList = 4;</code>
       */
      public Builder addAllInputList(
          java.lang.Iterable<java.lang.String> values) {
        ensureInputListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, inputList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string inputList = 4;</code>
       */
      public Builder clearInputList() {
        inputList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string inputList = 4;</code>
       */
      public Builder addInputListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureInputListIsMutable();
        inputList_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList textAreaList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTextAreaListIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          textAreaList_ = new com.google.protobuf.LazyStringArrayList(textAreaList_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string textAreaList = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getTextAreaListList() {
        return textAreaList_.getUnmodifiableView();
      }
      /**
       * <code>repeated string textAreaList = 5;</code>
       */
      public int getTextAreaListCount() {
        return textAreaList_.size();
      }
      /**
       * <code>repeated string textAreaList = 5;</code>
       */
      public java.lang.String getTextAreaList(int index) {
        return textAreaList_.get(index);
      }
      /**
       * <code>repeated string textAreaList = 5;</code>
       */
      public com.google.protobuf.ByteString
          getTextAreaListBytes(int index) {
        return textAreaList_.getByteString(index);
      }
      /**
       * <code>repeated string textAreaList = 5;</code>
       */
      public Builder setTextAreaList(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTextAreaListIsMutable();
        textAreaList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string textAreaList = 5;</code>
       */
      public Builder addTextAreaList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTextAreaListIsMutable();
        textAreaList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string textAreaList = 5;</code>
       */
      public Builder addAllTextAreaList(
          java.lang.Iterable<java.lang.String> values) {
        ensureTextAreaListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, textAreaList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string textAreaList = 5;</code>
       */
      public Builder clearTextAreaList() {
        textAreaList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string textAreaList = 5;</code>
       */
      public Builder addTextAreaListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureTextAreaListIsMutable();
        textAreaList_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object questionId_ = "";
      /**
       * <code>optional string questionId = 6;</code>
       */
      public java.lang.String getQuestionId() {
        java.lang.Object ref = questionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          questionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string questionId = 6;</code>
       */
      public com.google.protobuf.ByteString
          getQuestionIdBytes() {
        java.lang.Object ref = questionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          questionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string questionId = 6;</code>
       */
      public Builder setQuestionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        questionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string questionId = 6;</code>
       */
      public Builder clearQuestionId() {
        
        questionId_ = getDefaultInstance().getQuestionId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string questionId = 6;</code>
       */
      public Builder setQuestionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        questionId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protobuf.http.QuestionAnswerC)
    }

    // @@protoc_insertion_point(class_scope:protobuf.http.QuestionAnswerC)
    private static final protobuf.http.QuestionAnswer.QuestionAnswerC DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.http.QuestionAnswer.QuestionAnswerC();
    }

    public static protobuf.http.QuestionAnswer.QuestionAnswerC getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QuestionAnswerC>
        PARSER = new com.google.protobuf.AbstractParser<QuestionAnswerC>() {
      public QuestionAnswerC parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new QuestionAnswerC(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QuestionAnswerC> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QuestionAnswerC> getParserForType() {
      return PARSER;
    }

    public protobuf.http.QuestionAnswer.QuestionAnswerC getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface QuestionAnswerSOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.http.QuestionAnswerS)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 hOpCode = 1;</code>
     */
    int getHOpCode();
  }
  /**
   * Protobuf type {@code protobuf.http.QuestionAnswerS}
   */
  public  static final class QuestionAnswerS extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.http.QuestionAnswerS)
      QuestionAnswerSOrBuilder {
    // Use QuestionAnswerS.newBuilder() to construct.
    private QuestionAnswerS(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QuestionAnswerS() {
      hOpCode_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private QuestionAnswerS(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              hOpCode_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.http.QuestionAnswer.internal_static_protobuf_http_QuestionAnswerS_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.http.QuestionAnswer.internal_static_protobuf_http_QuestionAnswerS_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.http.QuestionAnswer.QuestionAnswerS.class, protobuf.http.QuestionAnswer.QuestionAnswerS.Builder.class);
    }

    public static final int HOPCODE_FIELD_NUMBER = 1;
    private int hOpCode_;
    /**
     * <code>optional int32 hOpCode = 1;</code>
     */
    public int getHOpCode() {
      return hOpCode_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hOpCode_ != 0) {
        output.writeInt32(1, hOpCode_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (hOpCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, hOpCode_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.http.QuestionAnswer.QuestionAnswerS)) {
        return super.equals(obj);
      }
      protobuf.http.QuestionAnswer.QuestionAnswerS other = (protobuf.http.QuestionAnswer.QuestionAnswerS) obj;

      boolean result = true;
      result = result && (getHOpCode()
          == other.getHOpCode());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + HOPCODE_FIELD_NUMBER;
      hash = (53 * hash) + getHOpCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.http.QuestionAnswer.QuestionAnswerS parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.http.QuestionAnswer.QuestionAnswerS parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.http.QuestionAnswer.QuestionAnswerS parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.http.QuestionAnswer.QuestionAnswerS parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.http.QuestionAnswer.QuestionAnswerS parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.http.QuestionAnswer.QuestionAnswerS parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.http.QuestionAnswer.QuestionAnswerS parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.http.QuestionAnswer.QuestionAnswerS parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.http.QuestionAnswer.QuestionAnswerS parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.http.QuestionAnswer.QuestionAnswerS parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.http.QuestionAnswer.QuestionAnswerS prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.http.QuestionAnswerS}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.http.QuestionAnswerS)
        protobuf.http.QuestionAnswer.QuestionAnswerSOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.http.QuestionAnswer.internal_static_protobuf_http_QuestionAnswerS_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.http.QuestionAnswer.internal_static_protobuf_http_QuestionAnswerS_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.http.QuestionAnswer.QuestionAnswerS.class, protobuf.http.QuestionAnswer.QuestionAnswerS.Builder.class);
      }

      // Construct using protobuf.http.QuestionAnswer.QuestionAnswerS.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        hOpCode_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.http.QuestionAnswer.internal_static_protobuf_http_QuestionAnswerS_descriptor;
      }

      public protobuf.http.QuestionAnswer.QuestionAnswerS getDefaultInstanceForType() {
        return protobuf.http.QuestionAnswer.QuestionAnswerS.getDefaultInstance();
      }

      public protobuf.http.QuestionAnswer.QuestionAnswerS build() {
        protobuf.http.QuestionAnswer.QuestionAnswerS result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.http.QuestionAnswer.QuestionAnswerS buildPartial() {
        protobuf.http.QuestionAnswer.QuestionAnswerS result = new protobuf.http.QuestionAnswer.QuestionAnswerS(this);
        result.hOpCode_ = hOpCode_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.http.QuestionAnswer.QuestionAnswerS) {
          return mergeFrom((protobuf.http.QuestionAnswer.QuestionAnswerS)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.http.QuestionAnswer.QuestionAnswerS other) {
        if (other == protobuf.http.QuestionAnswer.QuestionAnswerS.getDefaultInstance()) return this;
        if (other.getHOpCode() != 0) {
          setHOpCode(other.getHOpCode());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.http.QuestionAnswer.QuestionAnswerS parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.http.QuestionAnswer.QuestionAnswerS) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int hOpCode_ ;
      /**
       * <code>optional int32 hOpCode = 1;</code>
       */
      public int getHOpCode() {
        return hOpCode_;
      }
      /**
       * <code>optional int32 hOpCode = 1;</code>
       */
      public Builder setHOpCode(int value) {
        
        hOpCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 hOpCode = 1;</code>
       */
      public Builder clearHOpCode() {
        
        hOpCode_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protobuf.http.QuestionAnswerS)
    }

    // @@protoc_insertion_point(class_scope:protobuf.http.QuestionAnswerS)
    private static final protobuf.http.QuestionAnswer.QuestionAnswerS DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.http.QuestionAnswer.QuestionAnswerS();
    }

    public static protobuf.http.QuestionAnswer.QuestionAnswerS getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QuestionAnswerS>
        PARSER = new com.google.protobuf.AbstractParser<QuestionAnswerS>() {
      public QuestionAnswerS parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new QuestionAnswerS(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QuestionAnswerS> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QuestionAnswerS> getParserForType() {
      return PARSER;
    }

    public protobuf.http.QuestionAnswer.QuestionAnswerS getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_http_QuestionAnswerC_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_http_QuestionAnswerC_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_http_QuestionAnswerS_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_http_QuestionAnswerS_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024QuestionAnswer.proto\022\rprotobuf.http\"\220\001" +
      "\n\017QuestionAnswerC\022\017\n\007hOpCode\030\001 \001(\005\022\024\n\014qu" +
      "estionList\030\002 \003(\t\022\031\n\021questionOtherList\030\003 " +
      "\003(\t\022\021\n\tinputList\030\004 \003(\t\022\024\n\014textAreaList\030\005" +
      " \003(\t\022\022\n\nquestionId\030\006 \001(\t\"\"\n\017QuestionAnsw" +
      "erS\022\017\n\007hOpCode\030\001 \001(\005b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_http_QuestionAnswerC_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_http_QuestionAnswerC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_http_QuestionAnswerC_descriptor,
        new java.lang.String[] { "HOpCode", "QuestionList", "QuestionOtherList", "InputList", "TextAreaList", "QuestionId", });
    internal_static_protobuf_http_QuestionAnswerS_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_http_QuestionAnswerS_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_http_QuestionAnswerS_descriptor,
        new java.lang.String[] { "HOpCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
